wagtail/contrib/redirects/urls.py
from django.urls import path

from wagtail.contrib.redirects import views

app_name = "wagtailredirects"
urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.add, name="add"),
    path("<int:redirect_id>/", views.edit, name="edit"),
    path("<int:redirect_id>/delete/", views.delete, name="delete"),
    path("import/", views.start_import, name="start_import"),
    path("import/process/", views.process_import, name="process_import"),
    path("report", views.RedirectsReportView.as_view(), name="report"),
]

wagtail/contrib/redirects/templates/wagtailredirects/add.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% trans "Add redirect" %}{% endblock %}
{% block content %}
    {% trans "Add redirect" as add_red_str %}
    {% include "wagtailadmin/shared/header.html" with title=add_red_str icon="redirect" %}

    {% include "wagtailadmin/shared/non_field_errors.html" %}

    <form action="{% url 'wagtailredirects:add' %}" method="POST" class="nice-padding" novalidate>
        {% csrf_token %}

        <ul class="fields">
            {% for field in form.visible_fields %}
                {% include "wagtailadmin/shared/field_as_li.html" %}
            {% endfor %}

            <li>
                <input type="submit" value="{% trans 'Save' %}" class="button" />
            </li>
        </ul>
    </form>

{% endblock %}

{% block extra_js %}
    {{ block.super }}
    {% include "wagtailadmin/pages/_editor_js.html" %}
    {{ form.media.js }}
{% endblock %}

{% block extra_css %}
    {{ block.super }}
    {{ form.media.css }}
{% endblock %}

wagtail/contrib/redirects/templates/wagtailredirects/choose_import_file.html
{% extends "wagtailadmin/base.html" %}
{% load i18n wagtailadmin_tags %}
{% block titletag %}{% trans "Redirects" %}{% endblock %}

{% block content %}
    {% trans "Import redirects" as header_title %}
    {% include "wagtailadmin/shared/header.html" with title=header_title icon="redirect" %}

    <div class="nice-padding">
        <div class="help-block help-info">
            {% icon name='help' %}
            {% blocktrans trimmed %}
                <p>Select a file where redirects are separated into rows and contains the columns representing <code>from</code> and <code>to</code> (they can be named anything).</p>
                <p>After submitting you will be taken to a confirmation view where you can customize your redirects before import.</p>
            {% endblocktrans %}
        </div>
    </div>

    {% include "wagtailadmin/shared/non_field_errors.html" %}

    <form action="" method="POST" class="nice-padding" novalidate enctype="multipart/form-data">
        {% csrf_token %}

        <ul class="fields">
            {% for field in form.visible_fields %}
                {% include "wagtailadmin/shared/field_as_li.html" %}
            {% endfor %}

            <li>
                <input type="submit" value="{% trans 'Import' %}" class="button" />
            </li>
        </ul>
    </form>
{% endblock %}

wagtail/contrib/redirects/templates/wagtailredirects/confirm_delete.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% blocktrans trimmed with title=redirect.title %}Delete redirect {{ title }}{% endblocktrans %}{% endblock %}
{% block content %}
    {% trans "Delete" as delete_str %}
    {% include "wagtailadmin/shared/header.html" with title=delete_str subtitle=redirect.title icon="redirect" %}

    <div class="row row-flush nice-padding">
        <p>{% trans "Are you sure you want to delete this redirect?" %}</p>
        <form action="{% url 'wagtailredirects:delete' redirect.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="{% trans 'Yes, delete' %}" class="button serious" />
        </form>
    </div>

{% endblock %}

wagtail/contrib/redirects/templates/wagtailredirects/confirm_import.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}

{% block titletag %}{% trans "Confirm import" %}{% endblock %}
{% block content %}
    {% trans "Import redirects" as header_title %}
    {% trans "Confirm import" as header_subtitle %}
    {% include "wagtailadmin/shared/header.html" with title=header_title subtitle=header_subtitle icon="redirect" %}

    {% include "wagtailadmin/shared/non_field_errors.html" %}

    <form action="{% url 'wagtailredirects:process_import' %}" method="POST" class="nice-padding" novalidate enctype="multipart/form-data">
        {% csrf_token %}

        {% for field in form.hidden_fields %}{{ field }}{% endfor %}

        <ul class="fields">
            {% for field in form.visible_fields %}
                {% include "wagtailadmin/shared/field_as_li.html" %}
            {% endfor %}

            <li>
                <input type="submit" value="{% trans 'Confirm' %}" class="button" />
                <a href="{% url 'wagtailredirects:index' %}" class="button button-secondary">
                    {% trans 'Cancel' %}
                </a>
            </li>
        </ul>

        <h2>{% trans "Preview" %}</h2>
        <table class="listing listing-with-x-scroll">
            <thead>
                <tr>
                    {% for column in dataset.headers %}
                        <td>{{ column }}</td>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for row in dataset %}
                    <tr>
                        {% for column in row %}
                            <td>{{ column }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </form>
{% endblock %}

wagtail/contrib/redirects/templates/wagtailredirects/edit.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% blocktrans trimmed with title=redirect.title %}Editing {{ title }}{% endblocktrans %}{% endblock %}
{% block content %}
    {% trans "Editing" as editing_str %}
    {% include "wagtailadmin/shared/header.html" with title=editing_str subtitle=redirect.title icon="redirect" %}

    {% include "wagtailadmin/shared/non_field_errors.html" %}

    <form action="{% url 'wagtailredirects:edit' redirect.id %}" method="POST" class="nice-padding" novalidate>
        {% csrf_token %}

        <ul class="fields">
            {% for field in form.visible_fields %}
                {% include "wagtailadmin/shared/field_as_li.html" %}
            {% endfor %}

            <li>
                <input type="submit" value="{% trans 'Save' %}" class="button" />
                {% if user_can_delete %}
                    <a href="{% url 'wagtailredirects:delete' redirect.id %}" class="button button-secondary no">{% trans "Delete redirect" %}</a>
                {% endif %}
            </li>
        </ul>
    </form>

{% endblock %}

{% block extra_js %}
    {{ block.super }}
    {% include "wagtailadmin/pages/_editor_js.html" %}
    {{ form.media.js }}
{% endblock %}

{% block extra_css %}
    {{ block.super }}
    {{ form.media.css }}
{% endblock %}

wagtail/contrib/redirects/templates/wagtailredirects/import_summary.html
{% extends "wagtailadmin/base.html" %}
{% load i18n wagtailadmin_tags %}
{% block titletag %}{% trans "Summary" %}{% endblock %}
{% block content %}
    {% trans "Import redirects" as header_title %}
    {% trans "Summary" as header_subtitle %}
    {% include "wagtailadmin/shared/header.html" with title=header_title subtitle=header_subtitle icon="redirect" %}
    <section id="summary" class="nice-padding">
        <p class="help-block help-warning">
            {% icon name='warning' %}
            {% blocktrans trimmed with total=import_summary.total successes=import_summary.successes errors=import_summary.errors_count %}Found {{ total }} redirects, created {{ successes }} and found {{ errors }} errors.{% endblocktrans %}
        </p>

        <table class="listing">
            <thead>
                <tr>
                    <th>{% trans "From" %}</th>
                    <th>{% trans "To" %}</th>
                    <th>{% trans "Error" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for error in import_summary.errors %}
                    <tr>
                        {% for value in error %}
                            <td>{{ value }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <a href="{% url 'wagtailredirects:index' %}" class="button">{% trans "Continue" %}</a>
    </section>
{% endblock %}

wagtail/contrib/redirects/templates/wagtailredirects/index.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% load static wagtailadmin_tags %}

{% block bodyclass %}redirects{% endblock %}

{% block titletag %}{% trans "Redirects" %}{% endblock %}

{% block extra_js %}
    {{ block.super }}
    <script>
        window.headerSearch = {
            url: "{% url 'wagtailredirects:index' %}",
            termInput: "#id_q",
            targetOutput: "#redirects-results"
        }
    </script>
{% endblock %}

{% block content %}
    {% trans "Redirects" as redirects_str %}
    {% if user_can_add %}
        {% url "wagtailredirects:add" as add_link %}
        {% trans "Add redirect" as add_str %}
        {% url "wagtailredirects:start_import" as import_link %}
        {% url "wagtailredirects:report" as report_link %}
        {% trans "Import redirects" as import_str %}
        {% trans "Export redirects" as export_str %}
        {% fragment as redirect_actions %}
            <div class="dropdown dropdown-button match-width">
                <a href="{{ import_link }}" class="button bicolor button--icon">{% icon name="doc-full-inverse" wrapped=1 %}{{ import_str }}</a>
                <div class="dropdown-toggle">{% icon name="arrow-down" %}</div>
                <ul>
                    <li><a class="button bicolor button--icon" href="{{ report_link }}">{% icon name="download" wrapped=1 %}{{ export_str }}</a></li>
                </ul>
            </div>
        {% endfragment %}
        {% include "wagtailadmin/shared/header.html" with title=redirects_str icon="redirect" search_url="wagtailredirects:index" query_parameters=query_parameters action_url=add_link action_text=add_str action_icon="plus" extra_actions=redirect_actions %}


    {% else %}
        {% include "wagtailadmin/shared/header.html" with title=redirects_str icon="redirect" search_url="wagtailredirects:index" %}
    {% endif %}

    <div class="nice-padding">
        <div id="redirects-results" class="redirects">
            {% include "wagtailredirects/results.html" %}
        </div>
    </div>

{% endblock %}

wagtail/contrib/redirects/templates/wagtailredirects/list.html
{% load i18n %}
<table class="listing">
    <col width="35%"/>
    <col width="30%"/>
    <col width="25%"/>
    <col />
    <thead>
        <tr>
            <th class="title">
                {% if not is_searching %}
                    <a href="{% url 'wagtailredirects:index' %}{% if not ordering == "old_path" %}?ordering=old_path{% endif %}" class="icon icon-arrow-down-after {% if ordering == "old_path" %}teal{% endif %}">
                        {% trans "From" %}
                    </a>
                {% else %}
                    {% trans "From" %}
                {% endif %}
            </th>
            <th>{% trans "Site" %}</th>
            <th>{% trans "To" %}</th>
            <th class="type">{% trans "Type" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for redirect in redirects %}
            <tr>
                <td class="title">
                    <div class="title-wrapper"><a href="{% url 'wagtailredirects:edit' redirect.id %}" title="{% trans 'Edit this redirect' %}">{{ redirect.title }}</a></div>
                </td>
                <td>
                    {% if redirect.site %}{{ redirect.site }}{% endif %}
                </td>
                <td>
                    {% if redirect.redirect_page %}
                        <a href="{% url 'wagtailadmin_pages:edit' redirect.redirect_page.id %}" class="nolink">{{ redirect.redirect_page.title }}</a>
                    {% else %}
                        {{ redirect.link }}
                    {% endif %}
                </td>
                <td class="type"><div class="status-tag {% if redirect.is_permanent %}primary{% endif %}">{{ redirect.get_is_permanent_display }}</div></td>
            </tr>
        {% endfor %}
    </tbody>
</table>

wagtail/contrib/redirects/templates/wagtailredirects/results.html
{% load i18n %}
{% if redirects %}
    {% if query_string %}
        <h2 role="alert">
            {% blocktrans trimmed count counter=redirects.paginator.count %}
                There is {{ counter }} match
            {% plural %}
                There are {{ counter }} matches
            {% endblocktrans %}
        </h2>
    {% endif %}

    {% include "wagtailredirects/list.html" %}

    {% include "wagtailadmin/shared/pagination_nav.html" with items=redirects linkurl="wagtailredirects:index" %}
{% else %}
    {% if query_string %}
        <p role="alert">{% blocktrans trimmed %}Sorry, no redirects match "<em>{{ query_string }}</em>"{% endblocktrans %}</p>
    {% else %}
        {% url 'wagtailredirects:add' as wagtailredirects_add_redirect_url %}
        <p>{% blocktrans trimmed %}No redirects have been created. Why not <a href="{{ wagtailredirects_add_redirect_url }}">add one</a>?{% endblocktrans %}</p>
    {% endif %}
{% endif %}