wagtail/contrib/forms/urls.py
from django.urls import path

from wagtail.contrib.forms.views import (
    DeleteSubmissionsView,
    FormPagesListView,
    get_submissions_list_view,
)

app_name = "wagtailforms"
urlpatterns = [
    path("", FormPagesListView.as_view(), name="index"),
    path(
        "submissions/<int:page_id>/", get_submissions_list_view, name="list_submissions"
    ),
    path(
        "submissions/<int:page_id>/delete/",
        DeleteSubmissionsView.as_view(),
        name="delete_submissions",
    ),
]

wagtail/contrib/forms/templates/wagtailforms/confirm_delete.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% blocktrans trimmed with title=page.title %}Delete form data {{ title }}{% endblocktrans %}{% endblock %}
{% block bodyclass %}menu-explorer{% endblock %}

{% block content %}
    {% trans "Delete form data" as del_str %}
    {% include "wagtailadmin/shared/header.html" with title=del_str subtitle=page.title icon="doc-empty-inverse" %}

    <div class="nice-padding">
        <p>
            {% blocktrans trimmed count counter=submissions.count %}
                Are you sure you want to delete this form submission?
            {% plural %}
                Are you sure you want to delete these form submissions?
            {% endblocktrans %}
        </p>
        <form action="{% url 'wagtailforms:delete_submissions' page.id %}?{{ request.GET.urlencode }}" method="POST">
            {% csrf_token %}
            <input type="submit" value="{% trans 'Delete' %}" class="button serious">
        </form>
    </div>
{% endblock %}

wagtail/contrib/forms/templates/wagtailforms/index.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% trans "Forms" %}{% endblock %}
{% block content %}
    {% trans "Forms" as forms_str %}
    {% trans "Pages" as select_form_str %}
    {% include "wagtailadmin/shared/header_with_locale_selector.html" with title=forms_str subtitle=select_form_str icon="form" %}

    <div class="nice-padding">
        <div id="form-results" class="forms">
            {% include "wagtailforms/results_forms.html" %}
        </div>
    </div>
{% endblock %}

wagtail/contrib/forms/templates/wagtailforms/list_forms.html
{% load i18n %}
<table class="listing">
    <col width="50%"/>
    <col width="50%"/>
    <thead>
        <tr>
            <th class="title">{% trans "Title" %}</th>
            <th class="type">{% trans "Origin" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for fp in form_pages %}
            <tr>
                <td class="title">
                    <div class="title-wrapper"><a href="{% url 'wagtailforms:list_submissions' fp.id %}">{{ fp|capfirst }}</a></div>
                </td>
                <td class="type">
                    <small><a href="{% url 'wagtailadmin_pages:edit' fp.id %}" class="nolink">{{ fp.content_type.name |capfirst }} ({{ fp.content_type.app_label }}.{{ fp.content_type.model }})</a></small>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

wagtail/contrib/forms/templates/wagtailforms/list_submissions.html
{% load i18n %}
<div class="overflow">
    <table class="listing">
        <col />
        <col />
        <col />
        <thead>
            <tr>
                <th colspan="{{ data_headings|length|add:1 }}">
                    <button class="button no" id="delete-submissions" style="visibility: hidden">{% trans "Delete selected submissions" %}</button>
                </th>
            </tr>
            <tr>
                <th><input type="checkbox" id="select-all" /></th>
                {% for heading in data_headings %}
                    <th id="{{ heading.name }}" class="{% if heading.order %}ordered {{ heading.order }}{% endif %}">
                        {% if heading.order %}<a href="?order_by={% if heading.order == 'ascending' %}-{% endif %}{{ heading.name }}">{{ heading.label }}</a>{% else %}{{ heading.label }}{% endif %}
                    </th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for row in data_rows %}
                <tr>
                    <td>
                        <input type="checkbox" name="selected-submissions" class="select-submission" value="{{ row.model_id }}" />
                    </td>
                    {% for cell in row.fields %}
                        <td>
                            {{ cell }}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

wagtail/contrib/forms/templates/wagtailforms/results_forms.html
{% load i18n %}
{% if form_pages %}
    {% include "wagtailforms/list_forms.html" %}

    {% include "wagtailadmin/shared/pagination_nav.html" with items=page_obj linkurl="wagtailforms:index" %}
{% else %}
    <p>{% trans "No form pages have been created." %}</p>
{% endif %}

wagtail/contrib/forms/templates/wagtailforms/submissions_index.html
{% extends "wagtailadmin/base.html" %}
{% load i18n wagtailadmin_tags %}
{% block titletag %}{% blocktrans trimmed with form_title=form_page.title|capfirst %}Submissions of {{ form_title }}{% endblocktrans %}{% endblock %}
{% block extra_js %}
    {{ block.super }}

    <script>
        $.fn.datetimepicker.defaults.i18n.wagtail_custom_locale = {
            months: wagtailConfig.STRINGS.MONTHS,
            dayOfWeek: wagtailConfig.STRINGS.WEEKDAYS,
            dayOfWeekShort: wagtailConfig.STRINGS.WEEKDAYS_SHORT,
        }
        $.datetimepicker.setLocale('wagtail_custom_locale');

        $(function() {
            $('#id_date_from').datetimepicker({
                timepicker: false,
                format: 'Y-m-d',
            });
            $('#id_date_to').datetimepicker({
                timepicker: false,
                format: 'Y-m-d',
            });

            var selectAllCheckbox = document.getElementById('select-all');
            var deleteButton = document.getElementById('delete-submissions');

            function updateActions() {
                var submissionCheckboxes = $('input[type=checkbox].select-submission');
                var someSubmissionsSelected = submissionCheckboxes.is(':checked');
                var everySubmissionSelected = !submissionCheckboxes.is(':not(:checked)');

                // Select all box state
                if (everySubmissionSelected) {
                    // Every submission has been selected
                    selectAllCheckbox.checked = true;
                    selectAllCheckbox.indeterminate = false;
                } else if (someSubmissionsSelected) {
                    // At least one, but not all submissions have been selected
                    selectAllCheckbox.checked = false;
                    selectAllCheckbox.indeterminate = true;
                } else {
                    // No submissions have been selected
                    selectAllCheckbox.checked = false;
                    selectAllCheckbox.indeterminate = false;
                }

                // Delete button state
                if (someSubmissionsSelected) {
                    deleteButton.classList.remove('disabled')
                    deleteButton.style.visibility = "visible";
                } else {
                    deleteButton.classList.add('disabled')
                    deleteButton.style.visibility = "hidden";
                }
            }


            // Event handlers

            $(selectAllCheckbox).on('change', function() {
                let checked = this.checked;

                // Update checkbox states
                $('input[type=checkbox].select-submission').each(function() {
                    this.checked = checked;
                });

                updateActions();
            });

            $('input[type=checkbox].select-submission').on('change', function() {
                updateActions();
            });

            // initial call to updateActions to bring delete button state in sync with checkboxes
            // in the case that some checkboxes are pre-checked (which will be the case in some
            // browsers when using the back button)
            updateActions();
        });
    </script>
{% endblock %}
{% block content %}
    {% fragment as form_actions %}
        <div class="dropdown dropdown-button">
            <a href="?export=xlsx" class="button bicolor button--icon">
                {% icon name="download" wrapped=1 %}{% trans 'Download XLSX' %}
            </a>
            <div class="dropdown-toggle">{% icon name="arrow-down" %}</div>
            <ul>
                <li>
                    <a class="button bicolor button--icon" href="?export=csv">
                        {% icon name="download" wrapped=1 %}{% trans 'Download CSV' %}
                    </a>
                </li>
            </ul>
        </div>
    {% endfragment %}

    {% include "wagtailadmin/shared/header.html" with classname="w-header--no-border" title=page_title subtitle=form_page.title|capfirst icon="form" merged=1 extra_actions=form_actions %}

    <div class="report filterable">
        <div class="report__results w-overflow-y-hidden w-overflow-x-scroll w-pb-6">
            {% if submissions %}
                <form action="{% url 'wagtailforms:delete_submissions' form_page.id %}" method="get">
                    {% include "wagtailforms/list_submissions.html" %}
                    {% include "wagtailadmin/shared/pagination_nav.html" with items=page_obj %}
                </form>
            {% else %}
                <p class="no-results-message">{% blocktrans trimmed with title=form_page.title %}There have been no submissions of the '{{ title }}' form.{% endblocktrans %}</p>
            {% endif %}
        </div>
        <div class="filterable__filters">
            <h2>{% trans 'Filter' %}</h2>
            <form action="" method="get" novalidate>
                <button class="button button-longrunning" type="submit">{% icon name="spinner" %}{% trans 'Apply filters' %}</button>
                {% for field in select_date_form %}
                    {% include "wagtailadmin/shared/field_as_li.html" with field=field %}
                {% endfor %}
            </form>
        </div>
    </div>
{% endblock %}