wagtail/contrib/settings/urls.py
from django.urls import path

from . import views

app_name = "wagtailsettings"
urlpatterns = [
    path(
        "<slug:app_name>/<slug:model_name>/",
        views.redirect_to_relevant_instance,
        name="edit",
    ),
    path("<slug:app_name>/<slug:model_name>/<int:pk>/", views.edit, name="edit"),
]

wagtail/contrib/settings/templates/wagtailsettings/edit.html
{% extends "wagtailadmin/base.html" %}
{% load i18n wagtailadmin_tags %}

{% block titletag %}{% blocktrans trimmed %}Editing {{ instance }}{% endblocktrans %}{% endblock %}
{% block bodyclass %}menu-settings{% endblock %}

{% block content %}
    {% fragment as editing_actions %}
        {% if site_switcher %}
            <form method="get" id="settings-site-switch" novalidate>
                <label for="{{ site_switcher.site.id_for_label }}">
                    {% trans "Site" %}:
                </label>
                {{ site_switcher.site }}
            </form>
        {% endif %}
    {% endfragment %}
    {% include "wagtailadmin/shared/header.html" with title="Editing" icon="cogs" subtitle=setting_type_name|capfirst merged=1 extra_actions=editing_actions %}

    <form action="{% url 'wagtailsettings:edit' opts.app_label opts.model_name form_id %}" method="POST" novalidate{% if form.is_multipart %} enctype="multipart/form-data"{% endif %}>
        {% csrf_token %}

        <div class="nice-padding">
            {{ edit_handler.render_form_content }}
        </div>

        <footer class="footer">
            <ul>
                <li class="actions dropdown dropup match-width footer__container">
                    <button type="submit" class="button button-longrunning" data-clicked-text="{% trans 'Saving…' %}">{% icon name="spinner" %}<em>{% trans 'Save' %}</em></button>
                </li>
            </ul>
        </footer>
    </form>

{% endblock %}

{% block extra_css %}
    {{ block.super }}
    {{ media.css }}
{% endblock %}
{% block extra_js %}
    {{ block.super }}
    {% include "wagtailadmin/pages/_editor_js.html" %}
    {{ media.js }}
{% endblock %}

wagtail/contrib/settings/templates/wagtailsettings/index.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% trans "Settings" %}{% endblock %}
{% block bodyclass %}menu-settings{% endblock %}
{% block content %}

    {% include "wagtailadmin/shared/header.html" with title="Settings" icon="cogs" %}

    <div class="nice-padding">
        <ul class="listing">
            {% for name, description, content_type in setting_types %}
                <li>
                    <div class="row row-flush title">
                        <h2>
                            <a href="{% url 'wagtailsettings_edit' content_type.app_label content_type.model %}" class="col6">
                                {{ name|capfirst }}
                            </a>
                        </h2>
                        <small class="col6">{{ description }}</small>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}